#!/usr/bin/env sh

echo ">> blur"
img blur       < original.png > examples/blur.png
echo ">> brightness"
img brightness < original.png > examples/brightness.png
echo ">> channel"
img channel    < original.png > examples/channel.png
echo ">> contrast"
img contrast   < original.png > examples/contrast.png
echo ">> gamma"
img gamma      < original.png > examples/gamma.png
echo ">> greyscale"
img greyscale  < original.png > examples/greyscale.png
echo ">> hue"
img hue        < original.png > examples/hue.png
echo ">> hxl"
img hxl        < original.png > examples/hxl.png
echo ">> levels"
img levels     < original.png > examples/levels.png
echo ">> lightness"
img lightness  < original.png > examples/lightness.png
echo ">> pixelate"
img pixelate   < original.png > examples/pixelate.png
echo ">> pxl"
img pxl        < original.png > examples/pxl.png
echo ">> saturation"
img saturation < original.png > examples/saturation.png
echo ">> shuffle"
img shuffle    < original.png > examples/shuffle.png
echo ">> tint"
img tint       < original.png > examples/tint.png
echo ">> vxl"
img vxl        < original.png > examples/vxl.png

echo ">> blend"
if [ ! -d examples/blend ]; then
  mkdir examples/blend
fi

for m in `img blend --modes`; do
  echo "  >> $m"
  img blend --$m trans.png < original.png > examples/blend/$m.png
done

modelist=examples/blend/{$(echo `img blend --modes` | sed 's/\ /,/g')}.png
eval montage -label "%t" $modelist -geometry 134x200+4+3 examples/blend-modes.png
mv examples/blend/normal.png examples/blend.png
rm -r examples/blend


echo ">> composition example"
(img shuffle --horizontal | img hxl | img hue --by -20) < original.png > examples/composed.png


for f in `ls examples/*.png`; do
  convert $f "${f%.*}.jpg"
done

rm examples/*.png
jpegoptim examples/*.jpg
